### PR TITLE
Foundational stuff

### PR DESCRIPTION
**Pull request by brad**
Hi Sasha,
I think this app has a lot of potential, but I was really disappointed to find that it doesn't work on Lollipop. In my opinion, the first step to getting that working is to make sure there is a decent test framework in place, so I set about doing that. I started by doing some basic unit tests, trying to test nearly every line in the non-Android java code. That work is not complete but I got a good start on it. Next, I integrated all the tests from the https://github.com/sashavasko/WiFiAfterConnect.test project.

It seemed to me necessary as part of this work to restructure the project to more closely match what Android Studio and gradle expect. I built off of work by @gillius there.

I also set up integration with travis-ci. All you have to do is login to travis-ci.org with your github account and flip a switch to get the integration working with your fork. You can see it in action on my fork [here](https://travis-ci.org/brad/WiFiAfterConnect). The travis script posts the results to coveralls.io after a successful test run so you can keep tabs on how much of your code is currently covered by tests. With my updates, it stands at [47% test coverage](https://coveralls.io/r/brad/WiFiAfterConnect).

On another branch, I've been using an addition to the travis script that automatically builds a debug apk and posts it to [an S3 bucket](https://wifiafterconnect.s3.amazonaws.com/index.html) for convenience in installing/testing. Let me know if you want that and I'll make a PR.

I hope you like what I've done, and I have a lot more changes I'd like to work on in the future, such as:
- More tests
- Xfinity handler
- Android Wear component

### CODE REVIEW

**Comment by gillius** [comment]
Thanks for building on my work but you took too much of it (you must have squashed my commits). The first commit (ac3a734e253f89fb517d5109ff8d3e7e0d2fa0fb) I did was to enable Android Studio support. This might be the only one you need. The second commit (054e30e86285726b5bdd3adf722f6fb07b1896b6) is pretty non-controversial movement towards fixing the problem that forces the app to use WiFi even when cell is default route on Android, although that alone doesn't fix the issue. The latter two commits were shot-in-the-dark, aggressive attempts to make things work at the cost of burning battery and just trying to beat the OS to authenticate before it sees the portal. I didn't even want to push them but someone asked for it. It didn't even solve the problem so I highly recommend against it. I've yet to this day to find a solution to the issue. Current state for me is I get the "click here to sign in to WiFi" which I click then it immediately goes away because the app already signed in for me. But I still have to manually activate the notification to switch the OS's default route to WiFi.

**Comment by brad** [comment]
Thanks @gillius. You're right, I did squash those commits and I undid the changes from the other two

**Comment by gillius** [comment]
OK, I only looked at 779404765f700542091a1b2c5f9817f2958c27cc and didn't examine the others closely enough to see the reversion.

**Comment by brad** [comment]
I think you made a really good point @gillius so I redid the pull request, I think it's cleaner this time (#12)

**Pull request closed without merging**
